### ISSUE TITLE
Occasional error: UnboundLocalError: local variable 'inst_solar_pwr'

### ISSUE THREAD

**Issue by wdoekes** [wdoekes/pe32powerpy_pub#1]
```
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]: connection timeout, only poor values (OSError(113, "Connect call failed ('192.168.x.x', 1502)"), [Errno 113] Connect call failed ('192.168.x.x', 1502))
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]: Task exception was never retrieved
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]: future: <Task finished name='Task-3931759' coro=<Pe32Me162SunspecPublisher._publish() done, defined at /srv/pe32powerpy_pub/pe32powerpy_pub.py:110> exception=UnboundLocalError("local vari>
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]: Traceback (most recent call last):
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]:   File "/srv/pe32powerpy_pub/pe32powerpy_pub.py", line 123, in _publish
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]:     assert inst_pwr.unit == inst_solar_pwr.unit, (inst_pwr, inst_solar_pwr)
Jan 09 18:45:11 framboos.kiwi pe32powerpy_pub[4031]: UnboundLocalError: local variable 'inst_solar_pwr' referenced before assignment
```

**Comment by wdoekes** [comment]
Strikes again. This time because the solar thingy was gone.

Quick fix:
```diff
diff --git a/pe32powerpy_pub.py b/pe32powerpy_pub.py
index 694107b..3f1a739 100755
--- a/pe32powerpy_pub.py
+++ b/pe32powerpy_pub.py
@@ -115,9 +115,11 @@ class Pe32Me162SunspecPublisher(Pe32Me162Publisher):
         except ConnectionRefusedError as e:
             # [Errno 111] Connect call failed ('1.2.3.4', 1502)
             log.error('connection refused, only poor values (%r, %s)', e, e)
+            inst_solar_pwr = DecimalWithUnit.with_unit(0, 'W')
         except OSError as e:
             # [Errno 113] Connect call failed ('1.2.3.4', 1502)
             log.error('connection timeout, only poor values (%r, %s)', e, e)
+            inst_solar_pwr = DecimalWithUnit.with_unit(0, 'W')
 
         # Check and fix up values.
         assert inst_pwr.unit == inst_solar_pwr.unit, (inst_pwr, inst_solar_pwr)
```
```
Mar 13 17:54:34 framboos.kiwi pe32sunspecpy_pub[20912]: timeout, alas..
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]: connection timeout, only poor values (TimeoutError(110, "Connect call failed ('192.168.2.5', 1502)"), [Errno 110] Connect call failed ('192.168.x.x', 1502))
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]: Task exception was never retrieved
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]: future: <Task finished name='Task-8244619' coro=<Pe32Me162SunspecPublisher._publish() done, defined at /srv/pe32powerpy_pub/pe32powerpy_pub.py:110> exception=UnboundLocalError("local variable 'inst_solar_pwr' referenced before assignment")>
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]: Traceback (most recent call last):
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]:   File "/srv/pe32powerpy_pub/pe32powerpy_pub.py", line 123, in _publish
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]:     assert inst_pwr.unit == inst_solar_pwr.unit, (inst_pwr, inst_solar_pwr)
Mar 13 17:54:35 framboos.kiwi pe32powerpy_pub[4031]: UnboundLocalError: local variable 'inst_solar_pwr' referenced before assignment
Mar 13 17:54:39 framboos.kiwi pe32sunspecpy_pub[20912]: timeout, alas..
```
